### ISSUE TITLE
"Failed to get server hash" fix

### ISSUE THREAD

**Issue by khonkhortisan** [notmike101/BD-Server-Themes#11]
To keep using the id:
```
serverHash = document.querySelector('.wrapper-1BJsBx.selected-bZ3Lue').href.split('/')[4];
```
To use the server name instead:
```
serverHash = document.getElementsByClassName("name-3YKhmS da-name")[0].innerText
```

**Comment by notmike101** [comment]
As far as I'm aware, this plugin is no longer functional, with no intention of moving to a newer version for compatibility.

Am I mistaken?

**Comment by khonkhortisan** [comment]
I only needed to change that one line to make it functional. I first went with using the server name (da-name), then someone told me that string for still using the id (split 4), then they said that my solution for the name didn't work (even though it does for me) and they gave me the alternate line (aria-label) which I haven't tried.
~~I don't know whether this still works for complete themes, but~~* it worked with
```css
.inline {
    font-family: Stenodisplay Font,
        Consolas,Andale Mono WT,Andale Mono,Lucida Console,Lucida Sans Typewriter,DejaVu Sans Mono,Bitstream Vera Sans Mono,Liberation Mono,Nimbus Mono L,Monaco,Courier New,Courier,monospace
        !important;
    font-size:24px
        !important;
}
```
to convert stenography chords like `kat` to look like an actual keyboard, enabling and disabling the font when I switch to and from that server.
Whether or not there are plans for it, it can at least be made to work if someone wants it to.
Here's an image example of what I did with it (someone else's comment)
![imagen](https://user-images.githubusercontent.com/1996449/79700972-41219000-824e-11ea-93d1-2e9fcc2ff7f5.png)
![imagen](https://user-images.githubusercontent.com/1996449/79701008-9067c080-824e-11ea-9e82-73901905636b.png)
I like `KARPT` for carpet, and then `KAR/PET` can be "car pet" if I have a pet that spends a lot of time in my car

I just tried it with a retro theme on a different server id and it flashes Thank you! Please Enjoy! every time it loads, but it works with a complete theme.*

I just checked to make sure, I am using the exaxt same file as on here, `Server Specific Themes v1.0.0 by IRDeNial` Adding my change works instead of the line in the try, in the catch, or after the try/catch.
I assume deciding to maintain this may mean eventually changing that line again. Or adding multiple fallback methods for getting serverhash like
```js
        try {
            serverHash = $('.guild.selected a,.guild.active a').attr('href').split('/')[2];
        } catch(e) {
            try {
                serverHash = document.querySelector('.wrapper-1BJsBx.selected-bZ3Lue').href.split('/')[4];
            } catch(ee) {
                console.log("Failed to get server hash");
            }
        }
```
